services:
  langfuse-server:
    image: langfuse/langfuse:2.80
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${LANGFUSE_EXPOSE:-3101}:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-LANGFUSE_3k4jnf9cdn3orivnldskcvnb30reib3}@db:5432/${POSTGRES_DB:-postgres}
      - NEXTAUTH_SECRET=${LANGFUSE_SECRET:-dkvn20n2smicds02mi0499cn}
      - SALT=${SALT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY} # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=https://langufse.kamimind.ai
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-LANGFUSE_3k4jnf9cdn3orivnldskcvnb30reib3}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_EXPOSE:-5555}:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
